language: objective-c
osx_image: xcode10.2
before_install:
    - gem install cocoapods --quiet
    - gem install xcpretty --quiet
    - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script: rake test

