source 'https://github.com/CocoaPods/Specs.git'
project 'XLForm Tests'
inhibit_all_warnings!

platform :ios, '7.0'
target 'XLForm Tests' do
	pod 'Expecta', '~> 0.3.0'
	pod 'XLForm', :path => '../'
end
